### ISSUE TITLE
EventQueue_t size issue

### ISSUE THREAD

**Issue by matteofranceschini** [cocoOS/cocoOS#12]
Hi! 
I'm working with xc8 v2.05 on a PIC16, with 9 tasks and 12 events.

I noticed that in `os_event.h`  at [line 89](https://github.com/cocoOS/cocoOS/blob/a2a11a8f335e98e109ff975ea193b4de08b11e10/inc/os_event.h#L89) the `#ifdef` checks the `N_TOTAL_EVENTS` definition, but it looks like my compiler (and maybe others?) do not find N_TOTAL_EVENTS during compilation, therefore defining `EVENT_QUEUE_SIZE` equals to 1. 

In case of more than 8 events, this will overflow the event queue into the task data pointer. In the picture below, i have assigned to task 9 an event with id 11: as you can see it goes directly into the wrong memory area.

![image](https://user-images.githubusercontent.com/3541957/53346109-ab72c500-3916-11e9-8623-1675893b1efa.png)

By fixing this line of code, the result is as the second picture here: the eventlist has now two bytes of space in memory and does not overflow anymore.

![image](https://user-images.githubusercontent.com/3541957/53346389-39e74680-3917-11e9-857a-9c81d009a3c6.png)

hope this helps!

**Comment by ZanoZ** [comment]
Thanks for your works, :)
